import { Response, NextFunction } from "express";
import prisma from "../prisma/client";
import { ErrorHandler } from "@errors";
import type { AuthRequest } from "@middlewares";
const queueInclude={queue_group:{select:{id:true,name_uz:true,name_ru:true,name_en:true,prefix:true}}} as const;
async function dataFor(req:AuthRequest,companyId:string){const b=req.body;const data:any={};for(const k of ["name","name_uz","name_ru","name_en","label","icon_class","url","page_id","queue_group_id","parent_id","target","sort_order","is_visible","requires_auth"])if(b[k]!==undefined)data[k]=b[k];if(!data.name&&data.name_uz)data.name=data.name_uz;
 for(const [field,model] of [["parent_id","menu"],["queue_group_id","queueGroup"],["page_id","page"]]){if(data[field]){const target=await (prisma as any)[model].findFirst({where:{id:data[field],company_id:companyId}});if(!target)throw new ErrorHandler("Invalid menu destination",400);}}
 if(data.parent_id&&req.params.id){let parent=await prisma.menu.findUnique({where:{id:data.parent_id}});const visited=new Set<string>([req.params.id]);while(parent){if(visited.has(parent.id))throw new ErrorHandler("A menu cannot be nested inside itself",400);visited.add(parent.id);parent=parent.parent_id?await prisma.menu.findUnique({where:{id:parent.parent_id}}):null;}}
 return data;
}
export class MenuController{
 static async list(req:AuthRequest,res:Response,next:NextFunction){try{const companyId=req.user?.companyId||String(req.query.company_id||"");if(!companyId)return res.json({success:true,data:[]});const rows=await prisma.menu.findMany({where:{company_id:companyId},orderBy:[{sort_order:"asc"},{created_at:"asc"}],include:queueInclude});const map=new Map(rows.map(r=>[r.id,{...r,children:[] as any[]} ]));const roots:any[]=[];for(const row of map.values()){const parent=row.parent_id?map.get(row.parent_id):null;if(parent)parent.children.push(row);else roots.push(row);}res.json({success:true,data:roots});}catch(e){next(e);}}
 static async create(req:AuthRequest,res:Response,next:NextFunction){try{const companyId=req.user?.companyId||req.body.company_id;if(!companyId)throw new ErrorHandler("Company required",400);const data=await dataFor(req,companyId);if(!data.name?.trim())throw new ErrorHandler("Name required",400);const menu=await prisma.menu.create({data:{...data,company_id:companyId},include:queueInclude});res.status(201).json({success:true,data:menu});}catch(e){next(e);}}
 static async update(req:AuthRequest,res:Response,next:NextFunction){try{const existing=await prisma.menu.findUnique({where:{id:req.params.id}});if(!existing)throw new ErrorHandler("Menu not found",404);const data=await dataFor(req,existing.company_id);const menu=await prisma.menu.update({where:{id:existing.id},data,include:queueInclude});res.json({success:true,data:menu});}catch(e){next(e);}}
 static async remove(req:AuthRequest,res:Response,next:NextFunction){try{await prisma.$transaction(async tx=>{async function remove(id:string):Promise<void>{const children=await tx.menu.findMany({where:{parent_id:id},select:{id:true}});for(const c of children)await remove(c.id);await tx.menu.delete({where:{id}});}await remove(req.params.id);});res.json({success:true});}catch(e){next(e);}}
 static async reorder(req:AuthRequest,res:Response,next:NextFunction){try{const items=req.body.items as Array<{id:string;sort_order:number}>;if(!Array.isArray(items)||!items.length||items.length>1000||items.some(i=>!i.id||!Number.isInteger(i.sort_order)||i.sort_order<0)||new Set(items.map(i=>i.id)).size!==items.length)throw new ErrorHandler("Invalid menu order",400);const menus=await prisma.menu.findMany({where:{id:{in:items.map(i=>i.id)},...(req.user?.companyId?{company_id:req.user.companyId}:{})}});if(menus.length!==items.length||new Set(menus.map(m=>m.parent_id)).size!==1||new Set(menus.map(m=>m.company_id)).size!==1)throw new ErrorHandler("Only sibling menus from one company may be reordered",400);await prisma.$transaction(items.map(i=>prisma.menu.update({where:{id:i.id},data:{sort_order:i.sort_order}})));res.json({success:true});}catch(e){next(e);}}
}
